version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: slark
      POSTGRES_PASSWORD: slark
      POSTGRES_DB: bot_tg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://slark:slark@db/bot_tg_db
    ports:
      - "3001:3000"

volumes:
  postgres_data:
